Repository gitkoshelew/CC.ui, pull requests merged in 2022-12, with the labels that each got.

#25 Init ( README.md ) : CC.ui
  README.md
Labels: task, Frontend

#32 #14 main page cards
   postcss.config.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/Mocs/Moc.ts
  src/Types/CardTypes.ts
  src/components/cards/Card/Card.tsx
  src/components/cards/Cards.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/FullHeader/FullHeaderWrapper.tsx
  src/components/layout/header/Header/HeaderWrapper.tsx
  src/components/layout/header/HeaderButtons.tsx
  src/components/layout/header/HeaderContent.tsx
  src/components/layout/header/HeaderStack.tsx
  src/components/layout/header/HeaderStatistic.tsx
  src/styles/globals.css
  src/styles/theme/defaultTheme.ts
  tailwind.config.js
  yarn.lock
Labels: task, Frontend

#37 Dev fixed styles main page card
  package-lock.json
  src/components/cards/Card/Card.module.css
  src/components/cards/Card/Card.tsx
  src/components/cards/Cards.module.css
  src/components/cards/Cards.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Frontend

#40 [#18] feat: added prettier and lint
   postcss.config.js
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  jest.config.js
  package.json
  src/Mocs/CardMoc.ts
  src/Mocs/HeaderMoc.ts
  src/Mocs/NavigationMoc.ts
  src/Types/CardTypes.ts
  src/Types/NavigationTypes.ts
  src/assets/icons/AvatarIcon.tsx
  src/assets/icons/ListIcon.tsx
  src/assets/icons/MoonIcon.tsx
  src/components/cards/Card/Card.tsx
  src/components/cards/Cards.tsx
  src/components/common/types.ts
  src/components/layout/Layout.tsx
  src/components/layout/header/ButtonNums.tsx
  src/components/layout/header/DefaultHeader/DefaultHeader.tsx
  src/components/layout/header/DefaultHeader/DefaultHeaderWrapper.tsx
  src/components/layout/header/FullHeader/FullHeader.tsx
  src/components/layout/header/FullHeader/FullHeaderWrapper.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderAccount.tsx
  src/components/layout/header/HeaderContent.tsx
  src/components/layout/header/HeaderNavigation.tsx
  src/components/layout/header/HeaderStatistic.tsx
  src/components/layout/navigation/Category.tsx
  src/components/layout/navigation/Navigation.tsx
  src/components/layout/navigation/Sorting.tsx
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/stories/Organism/cards.stories.tsx
  src/stories/Organism/category.stories.tsx
  src/stories/Organism/header.stories.tsx
  src/stories/Organism/sorting.stories.tsx
  src/stories/pages/home.stories.tsx
  src/styles/theme/commonDefaultTheme.js
  src/styles/theme/darkTheme.ts
  src/styles/theme/defaultTheme.ts
  src/styles/theme/types.ts
  src/tests/index/index.test.tsx
  yarn.lock
Labels: task, Frontend

#46 add_styles_cards
  src/components/cards/Card/Card.module.css
  src/components/cards/Card/Card.tsx
Labels: task, Frontend

#50 add_styles_cards
  src/components/cards/Card/Card.tsx
Labels: Release 1.0.0, Frontend
