Repository gitkoshelew/CC.ui, pull requests merged in 2023-02, with the labels that each got.

#107 #103 add preloader v3
  src/components/common/Preloader/Preloader.tsx
  src/pages/_app.tsx
Labels: task, Frontend

#104 add difficulty select
  src/Mocs/NewTestMoc.ts
  src/components/new-test/QuestionBlock.tsx
  src/pages/create-test/index.tsx
  src/store/reducers/difficulty-reducer.ts
  src/store/reducers/questions-reducer.ts
  src/store/store.ts
Labels: task, Frontend

#112 Create registration
  package.json
  src/api/Instance/instance.ts
  src/api/authApi.ts
  src/components/new-test/QuestionBlock.tsx
  src/pages/registration/index.tsx
  src/store/reducers/auth-reducer.ts
  src/store/reducers/errorHandler-reducer.ts
  src/store/store.ts
  yarn.lock
Labels: task, Release 1.0.0, Frontend

#117 Get cards from server
  server/src/repositories/db.ts
  src/Mocs/CardMoc.ts
  src/Types/CardTypes.ts
  src/Types/types.ts
  src/api/Instance/instance.ts
  src/api/authApi.ts
  src/api/quizesApi.ts
  src/components/ErrorHandler/ErrorHandler.tsx
  src/components/cards/Card/Card.tsx
  src/components/cards/CardsWithQuizes.tsx
  src/components/common/types.ts
  src/components/layout/header/DefaultHeader/DefaultHeaderWrapper.tsx
  src/components/layout/header/FullHeader/FullHeaderWrapper.tsx
  src/pages/index.tsx
  src/pages/registration/index.tsx
  src/store/reducers/auth-reducer.ts
  src/store/reducers/quizes-reducer.ts
  src/store/store.ts
Labels: Frontend
