Repository gitkoshelew/CC.ui, pull requests merged in 2023-01, with the labels that each got.

#66 [#17]feat: create test pages
  src/Mocs/NewTestMoc.ts
  src/Mocs/QuizMock.ts
  src/Mocs/TimerMock.ts
  src/assets/icons/ArrowBottomIcon.tsx
  src/assets/icons/ArrowLeftIcon.tsx
  src/assets/icons/ArrowSuccessIcon.tsx
  src/assets/icons/ColonIcon.tsx
  src/assets/icons/PlusIcon.tsx
  src/components/cards/Card/Card.tsx
  src/components/common/ButtonBackHome.tsx
  src/components/layout/navigation/Category.tsx
  src/components/layout/navigation/Sorting.tsx
  src/components/new-test/ButtonSaveTest.tsx
  src/components/new-test/QuestionBlock.tsx
  src/components/new-test/SettingsBlock.tsx
  src/components/new-test/SuperButtonGroup.tsx
  src/components/new-test/SuperInput.tsx
  src/components/new-test/SuperSelect.tsx
  src/components/new-test/Timer.tsx
  src/components/new-test/WrapperNewTest.tsx
  src/pages/create-test/index.tsx
  src/pages/quiz/TestQuestions.tsx
  src/pages/quiz/index.tsx
  src/stories/pages/createTest.stories.tsx
  src/styles/theme/commonDefaultTheme.js
  src/styles/theme/defaultTheme.ts
Labels: task, Frontend

#67 [#17]fix: replaced quiz index, fix package.json
  .eslintrc.json
  package-lock.json
  package.json
  src/components/common/Tabs/QuestionTabs/QuestionTabs.tsx
  src/pages/quiz/index.tsx
  src/tests/index/index.test.tsx
  yarn.lock
Labels: bug, Frontend

#72 Fix readme
  README.md
Labels: task, Frontend

#85 Fix/83--was-fixed-creating-operation-for-questions-in-a-mock-server
  README.md
  package.json
  server/src/index.ts
  server/src/middlewares/express-validator-middleware.ts
  server/src/repositories/db.ts
  server/src/services/question-service.ts
  server/src/types/types.ts
Labels: bug, Frontend

#84 #42 1 table component res page
  src/Mocs/TableResultMoc.ts
  src/components/common/IncorrectAnswers/BasicTable.tsx
  src/components/common/IncorrectAnswers/incorrectAnswers.tsx
  src/stories/Organism/incorrectAnswer.stories.tsx
Labels: subtask, Frontend

#87 feature : Get cards from the mock server
  .eslintrc.json
  package.json
  server/src/errors/error.ts
  src/Mocs/CardMoc.ts
  src/api/Instance/instance.ts
  src/api/quizesApi.ts
  src/components/cards/Card/Card.tsx
  src/components/cards/CardsWithQuizes.tsx
  src/components/common/types.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/testPage/TestQuestions.tsx
  src/pages/testPage/index.tsx
  src/store/reducers/quizes-reducer.ts
  src/store/store.ts
  src/stories/Organism/cards.stories.tsx
  src/stories/pages/home.stories.tsx
  src/stories/pages/quiz.stories.tsx
  src/stories/pages/testPage.stories.tsx
  src/tests/index/index.test.tsx
  yarn.lock
Labels: task, Frontend

#98 Create cards
  src/api/quizesApi.ts
  src/components/layout/header/FullHeader/FullHeader.tsx
  src/components/new-test/ButtonSaveTest.tsx
  src/pages/index.tsx
  src/store/reducers/quizes-reducer.ts
Labels: task, Frontend

#101 Setup i18next
  .eslintrc.json
  next-i18next.config.js
  next.config.js
  package.json
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/en/testPage.json
  public/locales/ru/common.json
  public/locales/ru/home.json
  public/locales/ru/testPage.json
  src/api/quizesApi.ts
  src/components/cards/Card/Card.tsx
  src/components/cards/CardsWithQuizes.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/FullHeader/FullHeader.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderAccount.tsx
  src/components/layout/header/HeaderContent.tsx
  src/components/layout/header/HeaderNavigation.tsx
  src/components/layout/navigation/Category.tsx
  src/components/layout/navigation/Navigation.tsx
  src/components/layout/navigation/Sorting.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/testPage/TestQuestions.tsx
  src/pages/testPage/index.tsx
  src/store/reducers/quizes-reducer.ts
  src/styles/theme/defaultTheme.ts
  yarn.lock
Labels: task, Frontend
